version: "3.9"

volumes:
  mysql:
    driver: local

services:
  mysql:
    restart: unless-stopped
    container_name: mysql
    image: mysql:8.1.0
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - ./database.local.env
    ports:
      - "3306:3306"
    networks:
      - mysql

networks:
  mysql:
    name: mysql
    driver: bridge